# REST Client Extension

#############################
######      CORES      ######
#############################

### Cria uma nova COR
POST http://localhost:3600/api/v1/colors
content-type: application/json

{
  "name": "Ameixa",
  "hexColor": "#8E4585"
}


### Busca todas as CORES (1 <= perPage <= 20)
GET http://localhost:3600/api/v1/colors?perPage=5&page=1


### Busca COR pelo ID 
GET http://localhost:3600/api/v1/colors/1


### Atualiza COR pelo ID 
PATCH http://localhost:3600/api/v1/colors/3
content-type: application/json

{
  "name": "Vermelho Tomate",
  "hexColor": "#ef3519"
}

### Deleta COR pelo ID
DELETE  http://localhost:3600/api/v1/colors/2


##############################
######      CONTAS      ######
##############################

### Cria uma nova CONTA
POST http://localhost:3600/api/v1/accounts
content-type: application/json

{
  "name": "Default",
  "description": "Conta padrão."
}


### Busca todas as CONTAS (1 <= perPage <= 20)
GET http://localhost:3600/api/v1/accounts?perPage=5&page=1


### Busca CONTA pelo ID 
GET http://localhost:3600/api/v1/accounts/1


### Atualiza CONTA pelo ID 
PATCH http://localhost:3600/api/v1/accounts/1
content-type: application/json

{
  "name": "Padrão",
  "description": "Conta padrão em PT-BR."
}

### Deleta CONTA pelo ID
DELETE  http://localhost:3600/api/v1/accounts/1


##################################
######      TIMEFRAMES      ######
##################################

### Cria uma nova TIMEFRAME
POST http://localhost:3600/api/v1/timeframes
content-type: application/json

{
  "name": "1h",
  "description": "TIMEFRAME de 1 hora."
}


### Busca todos os TIMEFRAMES (1 <= perPage <= 20)
GET http://localhost:3600/api/v1/timeframes?perPage=5&page=1


### Busca TIMEFRAME pelo ID 
GET http://localhost:3600/api/v1/timeframes/1


### Atualiza TIMEFRAME pelo ID 
PATCH http://localhost:3600/api/v1/timeframes/1
content-type: application/json

{
  "name": "1H",
  "description": "TIMEFRAME de 1 hora."
}

### Deleta TIMEFRAME pelo ID
DELETE  http://localhost:3600/api/v1/timeframes/1


################################
######      MERCADOS      ######
################################

### Cria um novo MERCADO
POST http://localhost:3600/api/v1/markets
content-type: application/json

{
  "name": "Ação",
  "description": "MERCADO de ações à vista."
}


### Busca todos os MERCADOS (1 <= perPage <= 20)
GET http://localhost:3600/api/v1/markets?perPage=5&page=1


### Busca MERCADO pelo ID 
GET http://localhost:3600/api/v1/markets/1


### Atualiza MERCADO pelo ID 
PATCH http://localhost:3600/api/v1/markets/1
content-type: application/json

{
  "name": "Ações",
  "description": "MERCADO de ações à vista."
}

### Deleta MERCADO pelo ID
DELETE  http://localhost:3600/api/v1/markets/1


################################
######      SÍMBOLOS      ######
################################

### Cria um novo SÍMBOLO
POST http://localhost:3600/api/v1/symbols
content-type: application/json

{
  "name": "Ferbasa S.A.",
  "ticker": "FESA4",
  "idMarket": 1,
  "description": "Ação preferencial da Ferbasa, uma das maiores empresas de ferro do Brasil. Bolsa: B3. Setor: Materiais Básicos. Segmento: Mineração. País: Brasil. Moeda: BRL. Tipo: Ação. Data de listagem: 30/10/2002. Código ISIN: BRFESAACNPR5. Código CNPJ: 33.000.167/0001-01."
}


### Busca todos os SÍMBOLOS (1 <= perPage <= 20)
GET http://localhost:3600/api/v1/symbols?perPage=5&page=1


### Busca SÍMBOLO pelo ID 
GET http://localhost:3600/api/v1/symbols/1


### Atualiza SÍMBOLO pelo ID 
PATCH http://localhost:3600/api/v1/symbols/1
content-type: application/json

{
  "name": "Ferbasa S.A.",
  "ticker": "FESA4",
  "idMarket": 1,
  "description": "Ação preferencial da Ferbasa, uma das maiores empresas de ferro do Brasil. Bolsa: B3. Setor: Materiais Básicos. Segmento: Mineração. País: Brasil. Moeda: BRL. Tipo: Ação. Data de listagem: 30/10/2002. Código ISIN: BRFESAACNPR5. Código CNPJ: 33.000.167/0001-01."
}

### Deleta SÍMBOLO pelo ID
DELETE  http://localhost:3600/api/v1/symbols/1