# REST Client Extension

##############################
######      CONTAS      ######
##############################

### Cria uma nova CONTA
POST http://localhost:3600/api/v1/accounts
content-type: application/json

{
  "name": "Default",
  "description": "Conta padrão."
}

### Busca todas as CONTAS (1 <= perPage <= 20) (OPCIONAIS: perPage=5, page=3, name=Padrão)
GET http://localhost:3600/api/v1/accounts?perPage=5&page=1&name=Default

### Busca CONTA pelo ID 
GET http://localhost:3600/api/v1/accounts/1

### Atualiza CONTA pelo ID 
PATCH http://localhost:3600/api/v1/accounts/1
content-type: application/json

{
  "name": "Padrão",
  "description": "Conta padrão em PT-BR."
}

### Deleta CONTA pelo ID
DELETE  http://localhost:3600/api/v1/accounts/1