# REST Client Extension

##############################
######      SETUPS      ######
##############################

### Cria um novo SETUP
POST http://localhost:3600/api/v1/setups
content-type: application/json

{
  "name": "Inside Bar",
  "description": "Inside Bar é um padrão de continuação de tendência que ocorre quando uma barra (ou vela) está completamente contida dentro do intervalo da barra anterior. Isso indica indecisão no mercado e pode sinalizar uma possível continuação da tendência ou uma reversão. Tipo: Padrão de Continuação. Exemplo: Se o preço estiver em uma tendência de alta e formar um Inside Bar, isso pode indicar que a tendência de alta continuará após a consolidação representada pelo Inside Bar.",
  "idColor": 1
}

### Busca todos os SETUPS (1 <= perPage <= 20) (OPCIONAIS: perPage=5, page=3, name=Inside Bar)
GET http://localhost:3600/api/v1/setups?perPage=5&page=1&name=Inside+Bar

### Busca SETUP pelo ID 
GET http://localhost:3600/api/v1/setups/1

### Atualiza SETUP pelo ID 
PATCH http://localhost:3600/api/v1/setups/1
content-type: application/json

{
  "name": "Inside Bar",
  "description": "Inside Bar é um padrão de continuação de tendência que ocorre quando uma barra (ou vela) está completamente contida dentro do intervalo da barra anterior. Isso indica indecisão no mercado e pode sinalizar uma possível continuação da tendência ou uma reversão. Tipo: Padrão de Continuação. Exemplo: Se o preço estiver em uma tendência de alta e formar um Inside Bar, isso pode indicar que a tendência de alta continuará após a consolidação representada pelo Inside Bar.",
  "idColor": 1
}

### Deleta SETUP pelo ID
DELETE  http://localhost:3600/api/v1/setups/1