# REST Client Extension

################################
######      SÍMBOLOS      ######
################################

### Cria um novo SÍMBOLO
POST http://localhost:3600/api/v1/symbols
content-type: application/json

{
  "name": "Ferbasa S.A.",
  "ticker": "FESA4",
  "idMarket": 1,
  "description": "Ação preferencial da Ferbasa, uma das maiores empresas de ferro do Brasil. Bolsa: B3. Setor: Materiais Básicos. Segmento: Mineração. País: Brasil. Moeda: BRL. Tipo: Ação. Data de listagem: 30/10/2002. Código ISIN: BRFESAACNPR5. Código CNPJ: 33.000.167/0001-01."
}

### Busca todos os SÍMBOLOS (1 <= perPage <= 20) (OPCIONAIS: perPage=5, page=3, name=Ferbasa, ticker=FESA4)
GET http://localhost:3600/api/v1/symbols?perPage=5&page=1&name=Ferbasa&ticker=FESA4

### Busca SÍMBOLO pelo ID 
GET http://localhost:3600/api/v1/symbols/1

### Atualiza SÍMBOLO pelo ID 
PATCH http://localhost:3600/api/v1/symbols/1
content-type: application/json

{
  "name": "Ferbasa S.A.",
  "ticker": "FESA4",
  "idMarket": 1,
  "description": "Ação preferencial da Ferbasa, uma das maiores empresas de ferro do Brasil. Bolsa: B3. Setor: Materiais Básicos. Segmento: Mineração. País: Brasil. Moeda: BRL. Tipo: Ação. Data de listagem: 30/10/2002. Código ISIN: BRFESAACNPR5. Código CNPJ: 33.000.167/0001-01."
}

### Deleta SÍMBOLO pelo ID
DELETE  http://localhost:3600/api/v1/symbols/1